# Generated by Django 3.2.8 on 2021-11-03 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('parking_name', models.CharField(max_length=250, primary_key=True, serialize=False, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='FreeSpaces',
            fields=[
                ('free_spaces_number', models.IntegerField(verbose_name='Free spaces')),
                ('updated_at', models.DateTimeField(primary_key=True, serialize=False, verbose_name='Update date')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.parking', verbose_name='Parking')),
            ],
        ),
    ]
